name: 'AI Code Review'
description: 'Automate code reviews using AI.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key for AI responses.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Perform Static Analysis
      run: python ${{ github.action_path }}/src/analysis/static_analysis.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Run Analysis
      run: python ${{ github.action_path }}/src/analysis/code_review.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Post Feedback to GitHub
      run: python ${{ github.action_path }}/src/github/post_feedback.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Get Pull Request Details
      run: python ${{ github.action_path }}/src/github/github_interaction.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
