name: 'AI Code Review'
description: 'Automate code reviews using AI.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  LLAMA_API_KEY:
    description: 'Llama API key for AI responses.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Generate Review
      run: python ${{ github.action_path }}/analysis/code_review.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_API_KEY: ${{ inputs.LLAMA_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}  # Make sure this is correctly placed in the yaml
    - name: Upload Review Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: review-results
        path: review_results.txt
    - name: Post Feedback to GitHub
      run: python ${{ github.action_path }}/github/post_feedback.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_API_KEY: ${{ inputs.LLAMA_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
    - name: Get Pull Request Details
      run: python ${{ github.action_path }}/github/github_interaction.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_API_KEY: ${{ inputs.LLAMA_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
